# Generated by Django 2.2.7 on 2019-11-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=50)),
                ('E_Id', models.CharField(max_length=50, unique=True)),
                ('E_address', models.CharField(max_length=50)),
                ('E_salary', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
